//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuBienApp.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuBienApp.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.andresmedira.com.
        /// </summary>
        internal static string BaseAddress {
            get {
                return ResourceManager.GetString("BaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro que desea eliminar el registro seleccionado?.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string ConfirmDeleteMessageTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string ConfirmMessageAcept {
            get {
                return ResourceManager.GetString("ConfirmMessageAcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string ConfirmMessageCancel {
            get {
                return ResourceManager.GetString("ConfirmMessageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no fue creado correctamente..
        /// </summary>
        internal static string CustomerAddFailed {
            get {
                return ResourceManager.GetString("CustomerAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente fue creado correctamente..
        /// </summary>
        internal static string CustomerAddSuccess {
            get {
                return ResourceManager.GetString("CustomerAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de baños es requerido.
        /// </summary>
        internal static string CustomerBathrooms {
            get {
                return ResourceManager.GetString("CustomerBathrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no fue eliminado correctamente..
        /// </summary>
        internal static string CustomerDeleteFailed {
            get {
                return ResourceManager.GetString("CustomerDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue eliminado correctamente.
        /// </summary>
        internal static string CustomerDeleteSuccess {
            get {
                return ResourceManager.GetString("CustomerDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el nombre.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no fue actualizado correctamente..
        /// </summary>
        internal static string CustomerUpdateFailed {
            get {
                return ResourceManager.GetString("CustomerUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente fue actualizado correctamente..
        /// </summary>
        internal static string CustomerUpdateSuccess {
            get {
                return ResourceManager.GetString("CustomerUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error consultando información..
        /// </summary>
        internal static string GetFaild {
            get {
                return ResourceManager.GetString("GetFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información fue consultada correctamente..
        /// </summary>
        internal static string GetSuccess {
            get {
                return ResourceManager.GetString("GetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario es requerido..
        /// </summary>
        internal static string LoginIsEmailEntry {
            get {
                return ResourceManager.GetString("LoginIsEmailEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de correo no es válida..
        /// </summary>
        internal static string LoginIsEmailValid {
            get {
                return ResourceManager.GetString("LoginIsEmailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En este momento el ingreso a la app no se encuentra disponible..
        /// </summary>
        internal static string LoginIsFailed {
            get {
                return ResourceManager.GetString("LoginIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o la contraseña no es válido..
        /// </summary>
        internal static string LoginIsNotValid {
            get {
                return ResourceManager.GetString("LoginIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es requerida..
        /// </summary>
        internal static string LoginIsPasswordEntry {
            get {
                return ResourceManager.GetString("LoginIsPasswordEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienveni@ a SuBien..
        /// </summary>
        internal static string LoginIsSuccess {
            get {
                return ResourceManager.GetString("LoginIsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para realizar llamadas primero debe ingresar el número..
        /// </summary>
        internal static string PhoneCall {
            get {
                return ResourceManager.GetString("PhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( No camera available..
        /// </summary>
        internal static string PickPicture {
            get {
                return ResourceManager.GetString("PickPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Camera.
        /// </summary>
        internal static string PickPictureTitle {
            get {
                return ResourceManager.GetString("PickPictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad no fue ingresada correctamente..
        /// </summary>
        internal static string PropertyAddFailed {
            get {
                return ResourceManager.GetString("PropertyAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad fue ingresada correctamente..
        /// </summary>
        internal static string PropertyAddSuccess {
            get {
                return ResourceManager.GetString("PropertyAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contacto es requerido.
        /// </summary>
        internal static string PropertyContact {
            get {
                return ResourceManager.GetString("PropertyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no fue eliminado correctamente..
        /// </summary>
        internal static string PropertyDeleteFailed {
            get {
                return ResourceManager.GetString("PropertyDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue eliminado correctamente.
        /// </summary>
        internal static string PropertyDeleteSuccess {
            get {
                return ResourceManager.GetString("PropertyDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es requerido.
        /// </summary>
        internal static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El teléfono es requerido.
        /// </summary>
        internal static string PropertyPhone {
            get {
                return ResourceManager.GetString("PropertyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad no fue actualizada correctamente..
        /// </summary>
        internal static string PropertyUpdateFailed {
            get {
                return ResourceManager.GetString("PropertyUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad fue actualizada correctamente.
        /// </summary>
        internal static string PropertyUpdateSuccess {
            get {
                return ResourceManager.GetString("PropertyUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen no fue almacenada correctamente.
        /// </summary>
        internal static string SavePhotoAddFailed {
            get {
                return ResourceManager.GetString("SavePhotoAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen  fue almacenada correctamente.
        /// </summary>
        internal static string SavePhotoAddSuccess {
            get {
                return ResourceManager.GetString("SavePhotoAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick photo is not supported !.
        /// </summary>
        internal static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        internal static string TakePictureTitle {
            get {
                return ResourceManager.GetString("TakePictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TypeError {
            get {
                return ResourceManager.GetString("TypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string TypeInformation {
            get {
                return ResourceManager.GetString("TypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string TypeValue {
            get {
                return ResourceManager.GetString("TypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no fue actualizado.
        /// </summary>
        internal static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario actualizado correctamente.
        /// </summary>
        internal static string UserUpdateSuccess {
            get {
                return ResourceManager.GetString("UserUpdateSuccess", resourceCulture);
            }
        }
    }
}
